- name: Install golang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: Include task app_prereq
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: Download  golang
  ansible.builtin.shell: go mod init dispatch ; go get ; go build
  args:
    chdir: /app

- name: Include task Systemd_setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml