
- name: Install maven
  ansible.builtin.yum:
    name: maven
    state: installed

- name: Include task app_prereq
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: Download Maven dependences
  ansible.builtin.shell: mvn clean package ; mv target/{{component}}-1.0.jar {{component}}.jar
  args:
    chdir: /app

- name: Include task schema_setup
  ansible.builtin.import_tasks:
    file: schema_setup.yml

- name: Include task Systemd_setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml

- name: import prometheus
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter