#print_head "Installing the nodejs"
#sudo yum install https://rpm.nodesource.com/pub_18.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y &>>$log_file
#stat_check $?
#
#  #sudo yum install nodejs -y --setopt=nodesource-nodejs.module_hotfixes=1 &>>$log_file
#sudo yum install nodejs -y  &>>$log_file
#stat_check $?
#
#app_prereq
#
#print_head "NPM installing"
#npm install &>>$log_file
#stat_check $?
#
#schema_setup
#systemd

- name: configuring the nodejs repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/pub_18.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm

- name: Install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Include task list in play
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: Install the nodejs  dependence
  ansible.builtin.shell: npm install
  args:
    chdir: /app
