#print_head "Python installing "
#dnf install python36 gcc python3-devel -y &>>$log_file
#stat_check $?
#
#app_prereq
#
#print_head "pip install the requirements "
#pip3 install -r requirements.txt &>>$log_file
#stat_check $?
#
#print_head "Update Passwords in System Service file"
#sed -i -e "s|rabbitmq_appuser_password | ${rabbitmq_appuser_password}|" ${script_path}/payment.service &>>$log_file
#stat_check $?
#
#systemd

- name: Install maven
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Include task app_prereq
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: installing requirements
  ansible.builtin.shell: pip3 install -r requirements.txt
  args:
    chdir: /app

#- name: update password in system service file
#  ansible.builtin.shell: sed -i -e "s|rabbitmq_appuser_password | ${rabbitmq_appuser_password}|" ${script_path}/payment.service

- name: Include task schema_setup
  ansible.builtin.import_tasks:
    file: schema_setup.yml

- name: Include task Systemd_setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml
